Src/ClientManager.Web/Controllers/ClientController.cs
using ClientManager.Service.Interfaces;
using ClientManager.Web.Models;
using System.Web.Mvc;

namespace ClientManager.Web.Controllers
{

    public class ClientController : BaseController
    {
        private readonly IClientService _clientService;

        public ClientController()
        {
        }
        public ClientController(IClientService clientService)
        {
            _clientService = clientService;
        }
        //public ActionResult Index()
        //{
        //    return View();
        //}
        public ActionResult Index(ClientListFiltersModel filters)
        {
            return View(filters);
        }

        public ActionResult Detail(int id)
        {
            var client = _clientService.GetById(id);
            var clientForm = ClientForm.FromClient(client);
            return PartialView(clientForm);
        }

        public ActionResult Create()
        {
            var clientForm = new ClientForm();
            return PartialView(clientForm);
        }


        public ActionResult edit(int id)
        {
            var client = _clientService.GetById(id);
            var clientForm = ClientForm.FromClient(client);
            return PartialView(clientForm);
        }
    }
}

Src/ClientManager.Web/Controllers/PaymentController.cs
using ClientManager.Service.Interfaces;
using ClientManager.Web.Models;
using System.Web.Mvc;

namespace ClientManager.Web.Controllers
{

    public class PaymentController : BaseController
    {
        private readonly IPaymentService _paymentService;

        public PaymentController()
        {
        }
        public PaymentController(IPaymentService paymentService)
        {
            _paymentService = paymentService;
        }
        //public ActionResult Index()
        //{
        //    return View();
        //}
        public ActionResult Index(PaymentListFiltersModel filters)
        {
            return View(filters);
        }

        public ActionResult Detail(int id)
        {
            var payment = _paymentService.GetById(id);
            var paymentForm = PaymentForm.FromPayment(payment);
            return PartialView(paymentForm);
        }

        public ActionResult Create(int projectId)
        {
            var paymentForm = new PaymentForm();
            paymentForm.Secuencia = _paymentService.GetNextSequence(projectId);
            paymentForm.ProjectId = projectId;            
            return PartialView(paymentForm);
        }


        public ActionResult edit(int id)
        {
            var payment = _paymentService.GetById(id);
            var paymentForm = PaymentForm.FromPayment(payment);
            return PartialView(paymentForm);
        }
    }
}

Src/ClientManager.Web/Controllers/ProjectController.cs
using ClientManager.Service.Interfaces;
using ClientManager.Service.Models;
using ClientManager.Web.Models;
using System.Web.Mvc;

namespace ClientManager.Web.Controllers
{

    public class ProjectController : BaseController
    {
        private readonly IProjectService _projectService;

        public ProjectController()
        {
        }
        public ProjectController(IProjectService projectService)
        {
            _projectService = projectService;
        }
        //public ActionResult Index()
        //{
        //    return View();
        //}
        public ActionResult Index(ProjectListFiltersModel filters)
        {
            return View(filters);
        }

        public ActionResult Detail(int id)
        {
            var project = _projectService.GetById(id);
            var projectForm = ProjectForm.FromProject(project);
            return PartialView(projectForm);
        }

        public ActionResult Create()
        {
            var projectForm = new ProjectForm();
            return PartialView(projectForm);
        }


        public ActionResult edit(int id)
        {
            var project = _projectService.GetById(id);
            var projectForm = ProjectForm.FromProject(project);
            return PartialView(projectForm);
        }
    }
}

Src/ClientManager.Web/Controllers/TimeRecordController.cs
using ClientManager.Service.Interfaces;
using ClientManager.Web.Models;
using Microsoft.AspNet.Identity;
using System.Web.Mvc;

namespace ClientManager.Web.Controllers
{

    public class TimeRecordController : BaseController
    {
        private readonly ITimeRecordService _timeRecordService;

        public TimeRecordController()
        {
        }
        public TimeRecordController(ITimeRecordService timeRecordService)
        {
            _timeRecordService = timeRecordService;
        }
        //public ActionResult Index()
        //{
        //    return View();
        //}
        public ActionResult Index(TimeRecordListFilterModel filters)
        {
            return View(filters);
        }

        public ActionResult Detail(int id)
        {
            var timeRecord = _timeRecordService.GetById(id);
            var timeRecordForm = TimeRecordForm.FromTimeRecord(timeRecord);
            return PartialView(timeRecordForm);
        }

        public ActionResult Create(int projectId, int? userId)
        {
            var timeRecordForm = new TimeRecordForm();
            timeRecordForm.ProjectId = projectId;
            var usuario = userId;

            if (User.IsInRole("Developer"))
            {
                usuario = User.Identity.GetUserId<int>();
            }
            timeRecordForm.UserId = usuario;
            return PartialView(timeRecordForm);
        }


        public ActionResult Edit(int id)
        {
            var timeRecord = _timeRecordService.GetById(id);
            var timeRecordForm = TimeRecordForm.FromTimeRecord(timeRecord);
            return PartialView(timeRecordForm);
        }
    }
}

Src/ClientManager.Web/Views/Shared/_Alerts.cshtml
@using Framework.Common.Web.Alerts
@if (TempData.GetAlerts().Any())
{
	<script type="text/javascript">
		$(function() {
			@foreach (var alert in TempData.GetAlerts())
			{
				<text>
				window.alerts.showAlert({
					message: '@alert.Message.Replace("'", "\\'")',
					alertClass: '@alert.AlertClass'
				});
				</text>
			}			
		});
	</script>
}

Src/ClientManager.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body ng-app="app">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/" style="padding: 0;">
                    <img src="/Content/Images/logo.png" alt="" style="height: 40px; margin-top: 5px;" />
                </a>                
            </div>
            <div class="navbar-collapse collapse">
                @Html.Partial("_Menu")
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <span us-spinner spinner-theme="fullpage" spinner-key="spinner-fullpage" ng-class="{ 'spinner-with-overlay' : $$showOverlay }"></span>
    <div class="container body-content">
        @RenderSection("banner", required: false)
        <div class="container alert-container" style="padding-left: 0 !important;"></div>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; Admin</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/globalize")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/lib")
    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/angular/app")
    @RenderSection("scripts", required: false)
    @Html.Partial("_Alerts")
</body>
</html>

Src/ClientManager.Web/Views/Shared/_Menu.cshtml
<ul class="nav navbar-nav">

    <li>@Html.ActionLink("Clients", "Index", "Client")</li>
    <li>@Html.ActionLink("Projects", "Index", "Project")</li>
    <li>@Html.ActionLink("Payments", "Index", "Payment")</li>
    <li>@Html.ActionLink("TimeRecords", "Index", "TimeRecord")</li>


</ul>